// Generated by the protocol buffer compiler.  DO NOT EDIT!

package org.jetbrains.kotlin.serialization.builtins.nano;

@SuppressWarnings("hiding")
public interface BuiltInsProtoBuf {

  // extend .org.jetbrains.kotlin.serialization.Package {
  //   optional int32 package_fq_name = 151;
  public static final com.google.protobuf.nano.Extension<
      org.jetbrains.kotlin.serialization.nano.ProtoBuf.Package,
      java.lang.Integer> packageFqName =
          com.google.protobuf.nano.Extension.createPrimitiveTyped(
              com.google.protobuf.nano.Extension.TYPE_INT32,
              java.lang.Integer.class,
              1208L);

  // extend .org.jetbrains.kotlin.serialization.Class {
  //   repeated .org.jetbrains.kotlin.serialization.Annotation class_annotation = 150;
  public static final com.google.protobuf.nano.Extension<
      org.jetbrains.kotlin.serialization.nano.ProtoBuf.Class,
      org.jetbrains.kotlin.serialization.nano.ProtoBuf.Annotation[]> classAnnotation =
          com.google.protobuf.nano.Extension.createRepeatedMessageTyped(
              com.google.protobuf.nano.Extension.TYPE_MESSAGE,
              org.jetbrains.kotlin.serialization.nano.ProtoBuf.Annotation[].class,
              1202L);

  // extend .org.jetbrains.kotlin.serialization.Constructor {
  //   repeated .org.jetbrains.kotlin.serialization.Annotation constructor_annotation = 150;
  public static final com.google.protobuf.nano.Extension<
      org.jetbrains.kotlin.serialization.nano.ProtoBuf.Constructor,
      org.jetbrains.kotlin.serialization.nano.ProtoBuf.Annotation[]> constructorAnnotation =
          com.google.protobuf.nano.Extension.createRepeatedMessageTyped(
              com.google.protobuf.nano.Extension.TYPE_MESSAGE,
              org.jetbrains.kotlin.serialization.nano.ProtoBuf.Annotation[].class,
              1202L);

  // extend .org.jetbrains.kotlin.serialization.Function {
  //   repeated .org.jetbrains.kotlin.serialization.Annotation function_annotation = 150;
  public static final com.google.protobuf.nano.Extension<
      org.jetbrains.kotlin.serialization.nano.ProtoBuf.Function,
      org.jetbrains.kotlin.serialization.nano.ProtoBuf.Annotation[]> functionAnnotation =
          com.google.protobuf.nano.Extension.createRepeatedMessageTyped(
              com.google.protobuf.nano.Extension.TYPE_MESSAGE,
              org.jetbrains.kotlin.serialization.nano.ProtoBuf.Annotation[].class,
              1202L);

  // extend .org.jetbrains.kotlin.serialization.Property {
  //   repeated .org.jetbrains.kotlin.serialization.Annotation property_annotation = 150;
  public static final com.google.protobuf.nano.Extension<
      org.jetbrains.kotlin.serialization.nano.ProtoBuf.Property,
      org.jetbrains.kotlin.serialization.nano.ProtoBuf.Annotation[]> propertyAnnotation =
          com.google.protobuf.nano.Extension.createRepeatedMessageTyped(
              com.google.protobuf.nano.Extension.TYPE_MESSAGE,
              org.jetbrains.kotlin.serialization.nano.ProtoBuf.Annotation[].class,
              1202L);

  // extend .org.jetbrains.kotlin.serialization.Property {
  //   optional .org.jetbrains.kotlin.serialization.Annotation.Argument.Value compile_time_value = 151;
  public static final com.google.protobuf.nano.Extension<
      org.jetbrains.kotlin.serialization.nano.ProtoBuf.Property,
      org.jetbrains.kotlin.serialization.nano.ProtoBuf.Annotation.Argument.Value> compileTimeValue =
          com.google.protobuf.nano.Extension.createMessageTyped(
              com.google.protobuf.nano.Extension.TYPE_MESSAGE,
              org.jetbrains.kotlin.serialization.nano.ProtoBuf.Annotation.Argument.Value.class,
              1210L);

  // extend .org.jetbrains.kotlin.serialization.EnumEntry {
  //   repeated .org.jetbrains.kotlin.serialization.Annotation enum_entry_annotation = 150;
  public static final com.google.protobuf.nano.Extension<
      org.jetbrains.kotlin.serialization.nano.ProtoBuf.EnumEntry,
      org.jetbrains.kotlin.serialization.nano.ProtoBuf.Annotation[]> enumEntryAnnotation =
          com.google.protobuf.nano.Extension.createRepeatedMessageTyped(
              com.google.protobuf.nano.Extension.TYPE_MESSAGE,
              org.jetbrains.kotlin.serialization.nano.ProtoBuf.Annotation[].class,
              1202L);

  // extend .org.jetbrains.kotlin.serialization.ValueParameter {
  //   repeated .org.jetbrains.kotlin.serialization.Annotation parameter_annotation = 150;
  public static final com.google.protobuf.nano.Extension<
      org.jetbrains.kotlin.serialization.nano.ProtoBuf.ValueParameter,
      org.jetbrains.kotlin.serialization.nano.ProtoBuf.Annotation[]> parameterAnnotation =
          com.google.protobuf.nano.Extension.createRepeatedMessageTyped(
              com.google.protobuf.nano.Extension.TYPE_MESSAGE,
              org.jetbrains.kotlin.serialization.nano.ProtoBuf.Annotation[].class,
              1202L);

  // extend .org.jetbrains.kotlin.serialization.Type {
  //   repeated .org.jetbrains.kotlin.serialization.Annotation type_annotation = 150;
  public static final com.google.protobuf.nano.Extension<
      org.jetbrains.kotlin.serialization.nano.ProtoBuf.Type,
      org.jetbrains.kotlin.serialization.nano.ProtoBuf.Annotation[]> typeAnnotation =
          com.google.protobuf.nano.Extension.createRepeatedMessageTyped(
              com.google.protobuf.nano.Extension.TYPE_MESSAGE,
              org.jetbrains.kotlin.serialization.nano.ProtoBuf.Annotation[].class,
              1202L);

  // extend .org.jetbrains.kotlin.serialization.TypeParameter {
  //   repeated .org.jetbrains.kotlin.serialization.Annotation type_parameter_annotation = 150;
  public static final com.google.protobuf.nano.Extension<
      org.jetbrains.kotlin.serialization.nano.ProtoBuf.TypeParameter,
      org.jetbrains.kotlin.serialization.nano.ProtoBuf.Annotation[]> typeParameterAnnotation =
          com.google.protobuf.nano.Extension.createRepeatedMessageTyped(
              com.google.protobuf.nano.Extension.TYPE_MESSAGE,
              org.jetbrains.kotlin.serialization.nano.ProtoBuf.Annotation[].class,
              1202L);

  public static final class BuiltIns extends
      com.google.protobuf.nano.ExtendableMessageNano<BuiltIns> {

    private static volatile BuiltIns[] _emptyArray;
    public static BuiltIns[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new BuiltIns[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .org.jetbrains.kotlin.serialization.StringTable strings = 1;
    public org.jetbrains.kotlin.serialization.nano.ProtoBuf.StringTable strings;

    // optional .org.jetbrains.kotlin.serialization.QualifiedNameTable qualified_names = 2;
    public org.jetbrains.kotlin.serialization.nano.ProtoBuf.QualifiedNameTable qualifiedNames;

    // optional .org.jetbrains.kotlin.serialization.Package package = 3;
    public org.jetbrains.kotlin.serialization.nano.ProtoBuf.Package package_;

    // repeated .org.jetbrains.kotlin.serialization.Class class = 4;
    public org.jetbrains.kotlin.serialization.nano.ProtoBuf.Class[] class_;

    public BuiltIns() {
      clear();
    }

    public BuiltIns clear() {
      strings = null;
      qualifiedNames = null;
      package_ = null;
      class_ = org.jetbrains.kotlin.serialization.nano.ProtoBuf.Class.emptyArray();
      unknownFieldData = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.strings != null) {
        output.writeMessage(1, this.strings);
      }
      if (this.qualifiedNames != null) {
        output.writeMessage(2, this.qualifiedNames);
      }
      if (this.package_ != null) {
        output.writeMessage(3, this.package_);
      }
      if (this.class_ != null && this.class_.length > 0) {
        for (int i = 0; i < this.class_.length; i++) {
          org.jetbrains.kotlin.serialization.nano.ProtoBuf.Class element = this.class_[i];
          if (element != null) {
            output.writeMessage(4, element);
          }
        }
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.strings != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.strings);
      }
      if (this.qualifiedNames != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(2, this.qualifiedNames);
      }
      if (this.package_ != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(3, this.package_);
      }
      if (this.class_ != null && this.class_.length > 0) {
        for (int i = 0; i < this.class_.length; i++) {
          org.jetbrains.kotlin.serialization.nano.ProtoBuf.Class element = this.class_[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(4, element);
          }
        }
      }
      return size;
    }

    @Override
    public BuiltIns mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!storeUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.strings == null) {
              this.strings = new org.jetbrains.kotlin.serialization.nano.ProtoBuf.StringTable();
            }
            input.readMessage(this.strings);
            break;
          }
          case 18: {
            if (this.qualifiedNames == null) {
              this.qualifiedNames = new org.jetbrains.kotlin.serialization.nano.ProtoBuf.QualifiedNameTable();
            }
            input.readMessage(this.qualifiedNames);
            break;
          }
          case 26: {
            if (this.package_ == null) {
              this.package_ = new org.jetbrains.kotlin.serialization.nano.ProtoBuf.Package();
            }
            input.readMessage(this.package_);
            break;
          }
          case 34: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 34);
            int i = this.class_ == null ? 0 : this.class_.length;
            org.jetbrains.kotlin.serialization.nano.ProtoBuf.Class[] newArray =
                new org.jetbrains.kotlin.serialization.nano.ProtoBuf.Class[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.class_, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new org.jetbrains.kotlin.serialization.nano.ProtoBuf.Class();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new org.jetbrains.kotlin.serialization.nano.ProtoBuf.Class();
            input.readMessage(newArray[i]);
            this.class_ = newArray;
            break;
          }
        }
      }
    }

    public static BuiltIns parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new BuiltIns(), data);
    }

    public static BuiltIns parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new BuiltIns().mergeFrom(input);
    }
  }
}
