/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_jetbrains_jet_lang_resolve_objc_ObjCPackageFragmentProvider */

#ifndef _Included_org_jetbrains_jet_lang_resolve_objc_ObjCPackageFragmentProvider
#define _Included_org_jetbrains_jet_lang_resolve_objc_ObjCPackageFragmentProvider
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_jetbrains_jet_lang_resolve_objc_ObjCPackageFragmentProvider
 * Method:    buildObjCIndex
 * Signature: (Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_jetbrains_jet_lang_resolve_objc_ObjCPackageFragmentProvider_buildObjCIndex
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
