// Generated by the protocol buffer compiler.  DO NOT EDIT!

package org.jetbrains.kotlin.serialization.js.nano;

@SuppressWarnings("hiding")
public interface JsProtoBuf {

  // extend .org.jetbrains.kotlin.serialization.Class {
  //   repeated .org.jetbrains.kotlin.serialization.Annotation class_annotation = 130;
  public static final com.google.protobuf.nano.Extension<
      org.jetbrains.kotlin.serialization.nano.ProtoBuf.Class,
      org.jetbrains.kotlin.serialization.nano.ProtoBuf.Annotation[]> classAnnotation =
          com.google.protobuf.nano.Extension.createRepeatedMessageTyped(
              com.google.protobuf.nano.Extension.TYPE_MESSAGE,
              org.jetbrains.kotlin.serialization.nano.ProtoBuf.Annotation[].class,
              1042L);

  // extend .org.jetbrains.kotlin.serialization.Constructor {
  //   repeated .org.jetbrains.kotlin.serialization.Annotation constructor_annotation = 130;
  public static final com.google.protobuf.nano.Extension<
      org.jetbrains.kotlin.serialization.nano.ProtoBuf.Constructor,
      org.jetbrains.kotlin.serialization.nano.ProtoBuf.Annotation[]> constructorAnnotation =
          com.google.protobuf.nano.Extension.createRepeatedMessageTyped(
              com.google.protobuf.nano.Extension.TYPE_MESSAGE,
              org.jetbrains.kotlin.serialization.nano.ProtoBuf.Annotation[].class,
              1042L);

  // extend .org.jetbrains.kotlin.serialization.Function {
  //   repeated .org.jetbrains.kotlin.serialization.Annotation function_annotation = 130;
  public static final com.google.protobuf.nano.Extension<
      org.jetbrains.kotlin.serialization.nano.ProtoBuf.Function,
      org.jetbrains.kotlin.serialization.nano.ProtoBuf.Annotation[]> functionAnnotation =
          com.google.protobuf.nano.Extension.createRepeatedMessageTyped(
              com.google.protobuf.nano.Extension.TYPE_MESSAGE,
              org.jetbrains.kotlin.serialization.nano.ProtoBuf.Annotation[].class,
              1042L);

  // extend .org.jetbrains.kotlin.serialization.Property {
  //   repeated .org.jetbrains.kotlin.serialization.Annotation property_annotation = 130;
  public static final com.google.protobuf.nano.Extension<
      org.jetbrains.kotlin.serialization.nano.ProtoBuf.Property,
      org.jetbrains.kotlin.serialization.nano.ProtoBuf.Annotation[]> propertyAnnotation =
          com.google.protobuf.nano.Extension.createRepeatedMessageTyped(
              com.google.protobuf.nano.Extension.TYPE_MESSAGE,
              org.jetbrains.kotlin.serialization.nano.ProtoBuf.Annotation[].class,
              1042L);

  // extend .org.jetbrains.kotlin.serialization.Property {
  //   optional .org.jetbrains.kotlin.serialization.Annotation.Argument.Value compile_time_value = 131;
  public static final com.google.protobuf.nano.Extension<
      org.jetbrains.kotlin.serialization.nano.ProtoBuf.Property,
      org.jetbrains.kotlin.serialization.nano.ProtoBuf.Annotation.Argument.Value> compileTimeValue =
          com.google.protobuf.nano.Extension.createMessageTyped(
              com.google.protobuf.nano.Extension.TYPE_MESSAGE,
              org.jetbrains.kotlin.serialization.nano.ProtoBuf.Annotation.Argument.Value.class,
              1050L);

  // extend .org.jetbrains.kotlin.serialization.EnumEntry {
  //   repeated .org.jetbrains.kotlin.serialization.Annotation enum_entry_annotation = 130;
  public static final com.google.protobuf.nano.Extension<
      org.jetbrains.kotlin.serialization.nano.ProtoBuf.EnumEntry,
      org.jetbrains.kotlin.serialization.nano.ProtoBuf.Annotation[]> enumEntryAnnotation =
          com.google.protobuf.nano.Extension.createRepeatedMessageTyped(
              com.google.protobuf.nano.Extension.TYPE_MESSAGE,
              org.jetbrains.kotlin.serialization.nano.ProtoBuf.Annotation[].class,
              1042L);

  // extend .org.jetbrains.kotlin.serialization.ValueParameter {
  //   repeated .org.jetbrains.kotlin.serialization.Annotation parameter_annotation = 130;
  public static final com.google.protobuf.nano.Extension<
      org.jetbrains.kotlin.serialization.nano.ProtoBuf.ValueParameter,
      org.jetbrains.kotlin.serialization.nano.ProtoBuf.Annotation[]> parameterAnnotation =
          com.google.protobuf.nano.Extension.createRepeatedMessageTyped(
              com.google.protobuf.nano.Extension.TYPE_MESSAGE,
              org.jetbrains.kotlin.serialization.nano.ProtoBuf.Annotation[].class,
              1042L);

  // extend .org.jetbrains.kotlin.serialization.Type {
  //   repeated .org.jetbrains.kotlin.serialization.Annotation type_annotation = 130;
  public static final com.google.protobuf.nano.Extension<
      org.jetbrains.kotlin.serialization.nano.ProtoBuf.Type,
      org.jetbrains.kotlin.serialization.nano.ProtoBuf.Annotation[]> typeAnnotation =
          com.google.protobuf.nano.Extension.createRepeatedMessageTyped(
              com.google.protobuf.nano.Extension.TYPE_MESSAGE,
              org.jetbrains.kotlin.serialization.nano.ProtoBuf.Annotation[].class,
              1042L);

  // extend .org.jetbrains.kotlin.serialization.TypeParameter {
  //   repeated .org.jetbrains.kotlin.serialization.Annotation type_parameter_annotation = 130;
  public static final com.google.protobuf.nano.Extension<
      org.jetbrains.kotlin.serialization.nano.ProtoBuf.TypeParameter,
      org.jetbrains.kotlin.serialization.nano.ProtoBuf.Annotation[]> typeParameterAnnotation =
          com.google.protobuf.nano.Extension.createRepeatedMessageTyped(
              com.google.protobuf.nano.Extension.TYPE_MESSAGE,
              org.jetbrains.kotlin.serialization.nano.ProtoBuf.Annotation[].class,
              1042L);

  public static final class Classes extends
      com.google.protobuf.nano.ExtendableMessageNano<Classes> {

    private static volatile Classes[] _emptyArray;
    public static Classes[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Classes[0];
          }
        }
      }
      return _emptyArray;
    }

    // repeated int32 class_name = 1 [packed = true];
    public int[] className;

    public Classes() {
      clear();
    }

    public Classes clear() {
      className = com.google.protobuf.nano.WireFormatNano.EMPTY_INT_ARRAY;
      unknownFieldData = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.className != null && this.className.length > 0) {
        int dataSize = 0;
        for (int i = 0; i < this.className.length; i++) {
          int element = this.className[i];
          dataSize += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeInt32SizeNoTag(element);
        }
        output.writeRawVarint32(10);
        output.writeRawVarint32(dataSize);
        for (int i = 0; i < this.className.length; i++) {
          output.writeInt32NoTag(this.className[i]);
        }
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.className != null && this.className.length > 0) {
        int dataSize = 0;
        for (int i = 0; i < this.className.length; i++) {
          int element = this.className[i];
          dataSize += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeInt32SizeNoTag(element);
        }
        size += dataSize;
        size += 1;
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeRawVarint32Size(dataSize);
      }
      return size;
    }

    @Override
    public Classes mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!storeUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 8);
            int i = this.className == null ? 0 : this.className.length;
            int[] newArray = new int[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.className, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = input.readInt32();
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = input.readInt32();
            this.className = newArray;
            break;
          }
          case 10: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            // First pass to compute array length.
            int arrayLength = 0;
            int startPos = input.getPosition();
            while (input.getBytesUntilLimit() > 0) {
              input.readInt32();
              arrayLength++;
            }
            input.rewindToPosition(startPos);
            int i = this.className == null ? 0 : this.className.length;
            int[] newArray = new int[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.className, 0, newArray, 0, i);
            }
            for (; i < newArray.length; i++) {
              newArray[i] = input.readInt32();
            }
            this.className = newArray;
            input.popLimit(limit);
            break;
          }
        }
      }
    }

    public static Classes parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Classes(), data);
    }

    public static Classes parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Classes().mergeFrom(input);
    }
  }

  public static final class Library extends
      com.google.protobuf.nano.ExtendableMessageNano<Library> {

    public static final class FileEntry extends
        com.google.protobuf.nano.ExtendableMessageNano<FileEntry> {

      private static volatile FileEntry[] _emptyArray;
      public static FileEntry[] emptyArray() {
        // Lazily initializes the empty array
        if (_emptyArray == null) {
          synchronized (
              com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
            if (_emptyArray == null) {
              _emptyArray = new FileEntry[0];
            }
          }
        }
        return _emptyArray;
      }

      // required string path = 1;
      public java.lang.String path;

      // required bytes content = 2;
      public byte[] content;

      public FileEntry() {
        clear();
      }

      public FileEntry clear() {
        path = "";
        content = com.google.protobuf.nano.WireFormatNano.EMPTY_BYTES;
        unknownFieldData = null;
        cachedSize = -1;
        return this;
      }

      @Override
      public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
          throws java.io.IOException {
        output.writeString(1, this.path);
        output.writeBytes(2, this.content);
        super.writeTo(output);
      }

      @Override
      protected int computeSerializedSize() {
        int size = super.computeSerializedSize();
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.path);
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBytesSize(2, this.content);
        return size;
      }

      @Override
      public FileEntry mergeFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!storeUnknownField(input, tag)) {
                return this;
              }
              break;
            }
            case 10: {
              this.path = input.readString();
              break;
            }
            case 18: {
              this.content = input.readBytes();
              break;
            }
          }
        }
      }

      public static FileEntry parseFrom(byte[] data)
          throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
        return com.google.protobuf.nano.MessageNano.mergeFrom(new FileEntry(), data);
      }

      public static FileEntry parseFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        return new FileEntry().mergeFrom(input);
      }
    }

    private static volatile Library[] _emptyArray;
    public static Library[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new Library[0];
          }
        }
      }
      return _emptyArray;
    }

    // repeated .org.jetbrains.kotlin.serialization.js.Library.FileEntry entry = 1;
    public org.jetbrains.kotlin.serialization.js.nano.JsProtoBuf.Library.FileEntry[] entry;

    public Library() {
      clear();
    }

    public Library clear() {
      entry = org.jetbrains.kotlin.serialization.js.nano.JsProtoBuf.Library.FileEntry.emptyArray();
      unknownFieldData = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.entry != null && this.entry.length > 0) {
        for (int i = 0; i < this.entry.length; i++) {
          org.jetbrains.kotlin.serialization.js.nano.JsProtoBuf.Library.FileEntry element = this.entry[i];
          if (element != null) {
            output.writeMessage(1, element);
          }
        }
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.entry != null && this.entry.length > 0) {
        for (int i = 0; i < this.entry.length; i++) {
          org.jetbrains.kotlin.serialization.js.nano.JsProtoBuf.Library.FileEntry element = this.entry[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(1, element);
          }
        }
      }
      return size;
    }

    @Override
    public Library mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!storeUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 10);
            int i = this.entry == null ? 0 : this.entry.length;
            org.jetbrains.kotlin.serialization.js.nano.JsProtoBuf.Library.FileEntry[] newArray =
                new org.jetbrains.kotlin.serialization.js.nano.JsProtoBuf.Library.FileEntry[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.entry, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new org.jetbrains.kotlin.serialization.js.nano.JsProtoBuf.Library.FileEntry();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new org.jetbrains.kotlin.serialization.js.nano.JsProtoBuf.Library.FileEntry();
            input.readMessage(newArray[i]);
            this.entry = newArray;
            break;
          }
        }
      }
    }

    public static Library parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new Library(), data);
    }

    public static Library parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new Library().mergeFrom(input);
    }
  }
}
