// Generated by the protocol buffer compiler.  DO NOT EDIT!

package org.jetbrains.kotlin.serialization.jvm.nano;

@SuppressWarnings("hiding")
public interface JvmPackageTable {

  public static final class PackageTable extends
      com.google.protobuf.nano.ExtendableMessageNano<PackageTable> {

    private static volatile PackageTable[] _emptyArray;
    public static PackageTable[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new PackageTable[0];
          }
        }
      }
      return _emptyArray;
    }

    // repeated .org.jetbrains.kotlin.serialization.jvm.PackageParts package_parts = 1;
    public org.jetbrains.kotlin.serialization.jvm.nano.JvmPackageTable.PackageParts[] packageParts;

    public PackageTable() {
      clear();
    }

    public PackageTable clear() {
      packageParts = org.jetbrains.kotlin.serialization.jvm.nano.JvmPackageTable.PackageParts.emptyArray();
      unknownFieldData = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.packageParts != null && this.packageParts.length > 0) {
        for (int i = 0; i < this.packageParts.length; i++) {
          org.jetbrains.kotlin.serialization.jvm.nano.JvmPackageTable.PackageParts element = this.packageParts[i];
          if (element != null) {
            output.writeMessage(1, element);
          }
        }
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.packageParts != null && this.packageParts.length > 0) {
        for (int i = 0; i < this.packageParts.length; i++) {
          org.jetbrains.kotlin.serialization.jvm.nano.JvmPackageTable.PackageParts element = this.packageParts[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(1, element);
          }
        }
      }
      return size;
    }

    @Override
    public PackageTable mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!storeUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 10);
            int i = this.packageParts == null ? 0 : this.packageParts.length;
            org.jetbrains.kotlin.serialization.jvm.nano.JvmPackageTable.PackageParts[] newArray =
                new org.jetbrains.kotlin.serialization.jvm.nano.JvmPackageTable.PackageParts[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.packageParts, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new org.jetbrains.kotlin.serialization.jvm.nano.JvmPackageTable.PackageParts();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new org.jetbrains.kotlin.serialization.jvm.nano.JvmPackageTable.PackageParts();
            input.readMessage(newArray[i]);
            this.packageParts = newArray;
            break;
          }
        }
      }
    }

    public static PackageTable parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new PackageTable(), data);
    }

    public static PackageTable parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new PackageTable().mergeFrom(input);
    }
  }

  public static final class PackageParts extends
      com.google.protobuf.nano.ExtendableMessageNano<PackageParts> {

    private static volatile PackageParts[] _emptyArray;
    public static PackageParts[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new PackageParts[0];
          }
        }
      }
      return _emptyArray;
    }

    // required string package_fq_name = 1;
    public java.lang.String packageFqName;

    // repeated string class_name = 2;
    public java.lang.String[] className;

    public PackageParts() {
      clear();
    }

    public PackageParts clear() {
      packageFqName = "";
      className = com.google.protobuf.nano.WireFormatNano.EMPTY_STRING_ARRAY;
      unknownFieldData = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      output.writeString(1, this.packageFqName);
      if (this.className != null && this.className.length > 0) {
        for (int i = 0; i < this.className.length; i++) {
          java.lang.String element = this.className[i];
          if (element != null) {
            output.writeString(2, element);
          }
        }
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeStringSize(1, this.packageFqName);
      if (this.className != null && this.className.length > 0) {
        int dataCount = 0;
        int dataSize = 0;
        for (int i = 0; i < this.className.length; i++) {
          java.lang.String element = this.className[i];
          if (element != null) {
            dataCount++;
            dataSize += com.google.protobuf.nano.CodedOutputByteBufferNano
                .computeStringSizeNoTag(element);
          }
        }
        size += dataSize;
        size += 1 * dataCount;
      }
      return size;
    }

    @Override
    public PackageParts mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!storeUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.packageFqName = input.readString();
            break;
          }
          case 18: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 18);
            int i = this.className == null ? 0 : this.className.length;
            java.lang.String[] newArray = new java.lang.String[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.className, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = input.readString();
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = input.readString();
            this.className = newArray;
            break;
          }
        }
      }
    }

    public static PackageParts parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new PackageParts(), data);
    }

    public static PackageParts parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new PackageParts().mergeFrom(input);
    }
  }
}
