// Generated by the protocol buffer compiler.  DO NOT EDIT!

package org.jetbrains.kotlin.serialization.jvm.nano;

@SuppressWarnings("hiding")
public interface JvmProtoBuf {

  // extend .org.jetbrains.kotlin.serialization.Constructor {
  //   optional .org.jetbrains.kotlin.serialization.jvm.JvmMethodSignature constructor_signature = 100;
  public static final com.google.protobuf.nano.Extension<
      org.jetbrains.kotlin.serialization.nano.ProtoBuf.Constructor,
      org.jetbrains.kotlin.serialization.jvm.nano.JvmProtoBuf.JvmMethodSignature> constructorSignature =
          com.google.protobuf.nano.Extension.createMessageTyped(
              com.google.protobuf.nano.Extension.TYPE_MESSAGE,
              org.jetbrains.kotlin.serialization.jvm.nano.JvmProtoBuf.JvmMethodSignature.class,
              802L);

  // extend .org.jetbrains.kotlin.serialization.Function {
  //   optional .org.jetbrains.kotlin.serialization.jvm.JvmMethodSignature method_signature = 100;
  public static final com.google.protobuf.nano.Extension<
      org.jetbrains.kotlin.serialization.nano.ProtoBuf.Function,
      org.jetbrains.kotlin.serialization.jvm.nano.JvmProtoBuf.JvmMethodSignature> methodSignature =
          com.google.protobuf.nano.Extension.createMessageTyped(
              com.google.protobuf.nano.Extension.TYPE_MESSAGE,
              org.jetbrains.kotlin.serialization.jvm.nano.JvmProtoBuf.JvmMethodSignature.class,
              802L);

  // extend .org.jetbrains.kotlin.serialization.Property {
  //   optional .org.jetbrains.kotlin.serialization.jvm.JvmPropertySignature property_signature = 100;
  public static final com.google.protobuf.nano.Extension<
      org.jetbrains.kotlin.serialization.nano.ProtoBuf.Property,
      org.jetbrains.kotlin.serialization.jvm.nano.JvmProtoBuf.JvmPropertySignature> propertySignature =
          com.google.protobuf.nano.Extension.createMessageTyped(
              com.google.protobuf.nano.Extension.TYPE_MESSAGE,
              org.jetbrains.kotlin.serialization.jvm.nano.JvmProtoBuf.JvmPropertySignature.class,
              802L);

  // extend .org.jetbrains.kotlin.serialization.Type {
  //   repeated .org.jetbrains.kotlin.serialization.Annotation type_annotation = 100;
  public static final com.google.protobuf.nano.Extension<
      org.jetbrains.kotlin.serialization.nano.ProtoBuf.Type,
      org.jetbrains.kotlin.serialization.nano.ProtoBuf.Annotation[]> typeAnnotation =
          com.google.protobuf.nano.Extension.createRepeatedMessageTyped(
              com.google.protobuf.nano.Extension.TYPE_MESSAGE,
              org.jetbrains.kotlin.serialization.nano.ProtoBuf.Annotation[].class,
              802L);

  // extend .org.jetbrains.kotlin.serialization.Type {
  //   optional bool is_raw = 101;
  public static final com.google.protobuf.nano.Extension<
      org.jetbrains.kotlin.serialization.nano.ProtoBuf.Type,
      java.lang.Boolean> isRaw =
          com.google.protobuf.nano.Extension.createPrimitiveTyped(
              com.google.protobuf.nano.Extension.TYPE_BOOL,
              java.lang.Boolean.class,
              808L);

  // extend .org.jetbrains.kotlin.serialization.TypeParameter {
  //   repeated .org.jetbrains.kotlin.serialization.Annotation type_parameter_annotation = 100;
  public static final com.google.protobuf.nano.Extension<
      org.jetbrains.kotlin.serialization.nano.ProtoBuf.TypeParameter,
      org.jetbrains.kotlin.serialization.nano.ProtoBuf.Annotation[]> typeParameterAnnotation =
          com.google.protobuf.nano.Extension.createRepeatedMessageTyped(
              com.google.protobuf.nano.Extension.TYPE_MESSAGE,
              org.jetbrains.kotlin.serialization.nano.ProtoBuf.Annotation[].class,
              802L);

  // extend .org.jetbrains.kotlin.serialization.Class {
  //   optional int32 class_module_name = 101;
  public static final com.google.protobuf.nano.Extension<
      org.jetbrains.kotlin.serialization.nano.ProtoBuf.Class,
      java.lang.Integer> classModuleName =
          com.google.protobuf.nano.Extension.createPrimitiveTyped(
              com.google.protobuf.nano.Extension.TYPE_INT32,
              java.lang.Integer.class,
              808L);

  // extend .org.jetbrains.kotlin.serialization.Package {
  //   optional int32 package_module_name = 101;
  public static final com.google.protobuf.nano.Extension<
      org.jetbrains.kotlin.serialization.nano.ProtoBuf.Package,
      java.lang.Integer> packageModuleName =
          com.google.protobuf.nano.Extension.createPrimitiveTyped(
              com.google.protobuf.nano.Extension.TYPE_INT32,
              java.lang.Integer.class,
              808L);

  public static final class StringTableTypes extends
      com.google.protobuf.nano.ExtendableMessageNano<StringTableTypes> {

    public static final class Record extends
        com.google.protobuf.nano.ExtendableMessageNano<Record> {

      // enum Operation
      public interface Operation {
        public static final int NONE = 0;
        public static final int INTERNAL_TO_CLASS_ID = 1;
        public static final int DESC_TO_CLASS_ID = 2;
      }

      private static volatile Record[] _emptyArray;
      public static Record[] emptyArray() {
        // Lazily initializes the empty array
        if (_emptyArray == null) {
          synchronized (
              com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
            if (_emptyArray == null) {
              _emptyArray = new Record[0];
            }
          }
        }
        return _emptyArray;
      }

      private int bitField0_;

      // optional int32 range = 1 [default = 1];
      private int range_;
      public int getRange() {
        return range_;
      }
      public Record setRange(int value) {
        range_ = value;
        bitField0_ |= 0x00000001;
        return this;
      }
      public boolean hasRange() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      public Record clearRange() {
        range_ = 1;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      // optional int32 predefined_index = 2;
      private int predefinedIndex_;
      public int getPredefinedIndex() {
        return predefinedIndex_;
      }
      public Record setPredefinedIndex(int value) {
        predefinedIndex_ = value;
        bitField0_ |= 0x00000002;
        return this;
      }
      public boolean hasPredefinedIndex() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      public Record clearPredefinedIndex() {
        predefinedIndex_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      // optional string string = 6;
      private java.lang.String string_;
      public java.lang.String getString() {
        return string_;
      }
      public Record setString(java.lang.String value) {
        if (value == null) {
          throw new java.lang.NullPointerException();
        }
        string_ = value;
        bitField0_ |= 0x00000004;
        return this;
      }
      public boolean hasString() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      public Record clearString() {
        string_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      // optional .org.jetbrains.kotlin.serialization.jvm.StringTableTypes.Record.Operation operation = 3 [default = NONE];
      private int operation_;
      public int getOperation() {
        return operation_;
      }
      public Record setOperation(int value) {
        operation_ = value;
        bitField0_ |= 0x00000008;
        return this;
      }
      public boolean hasOperation() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      public Record clearOperation() {
        operation_ = org.jetbrains.kotlin.serialization.jvm.nano.JvmProtoBuf.StringTableTypes.Record.Operation.NONE;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      // repeated int32 substring_index = 4 [packed = true];
      public int[] substringIndex;

      // repeated int32 replace_char = 5 [packed = true];
      public int[] replaceChar;

      public Record() {
        clear();
      }

      public Record clear() {
        bitField0_ = 0;
        range_ = 1;
        predefinedIndex_ = 0;
        string_ = "";
        operation_ = org.jetbrains.kotlin.serialization.jvm.nano.JvmProtoBuf.StringTableTypes.Record.Operation.NONE;
        substringIndex = com.google.protobuf.nano.WireFormatNano.EMPTY_INT_ARRAY;
        replaceChar = com.google.protobuf.nano.WireFormatNano.EMPTY_INT_ARRAY;
        unknownFieldData = null;
        cachedSize = -1;
        return this;
      }

      @Override
      public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
          throws java.io.IOException {
        if (((bitField0_ & 0x00000001) != 0)) {
          output.writeInt32(1, range_);
        }
        if (((bitField0_ & 0x00000002) != 0)) {
          output.writeInt32(2, predefinedIndex_);
        }
        if (((bitField0_ & 0x00000008) != 0)) {
          output.writeInt32(3, operation_);
        }
        if (this.substringIndex != null && this.substringIndex.length > 0) {
          int dataSize = 0;
          for (int i = 0; i < this.substringIndex.length; i++) {
            int element = this.substringIndex[i];
            dataSize += com.google.protobuf.nano.CodedOutputByteBufferNano
                .computeInt32SizeNoTag(element);
          }
          output.writeRawVarint32(34);
          output.writeRawVarint32(dataSize);
          for (int i = 0; i < this.substringIndex.length; i++) {
            output.writeInt32NoTag(this.substringIndex[i]);
          }
        }
        if (this.replaceChar != null && this.replaceChar.length > 0) {
          int dataSize = 0;
          for (int i = 0; i < this.replaceChar.length; i++) {
            int element = this.replaceChar[i];
            dataSize += com.google.protobuf.nano.CodedOutputByteBufferNano
                .computeInt32SizeNoTag(element);
          }
          output.writeRawVarint32(42);
          output.writeRawVarint32(dataSize);
          for (int i = 0; i < this.replaceChar.length; i++) {
            output.writeInt32NoTag(this.replaceChar[i]);
          }
        }
        if (((bitField0_ & 0x00000004) != 0)) {
          output.writeString(6, string_);
        }
        super.writeTo(output);
      }

      @Override
      protected int computeSerializedSize() {
        int size = super.computeSerializedSize();
        if (((bitField0_ & 0x00000001) != 0)) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeInt32Size(1, range_);
        }
        if (((bitField0_ & 0x00000002) != 0)) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeInt32Size(2, predefinedIndex_);
        }
        if (((bitField0_ & 0x00000008) != 0)) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(3, operation_);
        }
        if (this.substringIndex != null && this.substringIndex.length > 0) {
          int dataSize = 0;
          for (int i = 0; i < this.substringIndex.length; i++) {
            int element = this.substringIndex[i];
            dataSize += com.google.protobuf.nano.CodedOutputByteBufferNano
                .computeInt32SizeNoTag(element);
          }
          size += dataSize;
          size += 1;
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeRawVarint32Size(dataSize);
        }
        if (this.replaceChar != null && this.replaceChar.length > 0) {
          int dataSize = 0;
          for (int i = 0; i < this.replaceChar.length; i++) {
            int element = this.replaceChar[i];
            dataSize += com.google.protobuf.nano.CodedOutputByteBufferNano
                .computeInt32SizeNoTag(element);
          }
          size += dataSize;
          size += 1;
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeRawVarint32Size(dataSize);
        }
        if (((bitField0_ & 0x00000004) != 0)) {
          size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeStringSize(6, string_);
        }
        return size;
      }

      @Override
      public Record mergeFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              return this;
            default: {
              if (!storeUnknownField(input, tag)) {
                return this;
              }
              break;
            }
            case 8: {
              range_ = input.readInt32();
              bitField0_ |= 0x00000001;
              break;
            }
            case 16: {
              predefinedIndex_ = input.readInt32();
              bitField0_ |= 0x00000002;
              break;
            }
            case 24: {
              int value = input.readInt32();
              switch (value) {
                case org.jetbrains.kotlin.serialization.jvm.nano.JvmProtoBuf.StringTableTypes.Record.Operation.NONE:
                case org.jetbrains.kotlin.serialization.jvm.nano.JvmProtoBuf.StringTableTypes.Record.Operation.INTERNAL_TO_CLASS_ID:
                case org.jetbrains.kotlin.serialization.jvm.nano.JvmProtoBuf.StringTableTypes.Record.Operation.DESC_TO_CLASS_ID:
                  operation_ = value;
                  bitField0_ |= 0x00000008;
                  break;
              }
              break;
            }
            case 32: {
              int arrayLength = com.google.protobuf.nano.WireFormatNano
                  .getRepeatedFieldArrayLength(input, 32);
              int i = this.substringIndex == null ? 0 : this.substringIndex.length;
              int[] newArray = new int[i + arrayLength];
              if (i != 0) {
                java.lang.System.arraycopy(this.substringIndex, 0, newArray, 0, i);
              }
              for (; i < newArray.length - 1; i++) {
                newArray[i] = input.readInt32();
                input.readTag();
              }
              // Last one without readTag.
              newArray[i] = input.readInt32();
              this.substringIndex = newArray;
              break;
            }
            case 34: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              // First pass to compute array length.
              int arrayLength = 0;
              int startPos = input.getPosition();
              while (input.getBytesUntilLimit() > 0) {
                input.readInt32();
                arrayLength++;
              }
              input.rewindToPosition(startPos);
              int i = this.substringIndex == null ? 0 : this.substringIndex.length;
              int[] newArray = new int[i + arrayLength];
              if (i != 0) {
                java.lang.System.arraycopy(this.substringIndex, 0, newArray, 0, i);
              }
              for (; i < newArray.length; i++) {
                newArray[i] = input.readInt32();
              }
              this.substringIndex = newArray;
              input.popLimit(limit);
              break;
            }
            case 40: {
              int arrayLength = com.google.protobuf.nano.WireFormatNano
                  .getRepeatedFieldArrayLength(input, 40);
              int i = this.replaceChar == null ? 0 : this.replaceChar.length;
              int[] newArray = new int[i + arrayLength];
              if (i != 0) {
                java.lang.System.arraycopy(this.replaceChar, 0, newArray, 0, i);
              }
              for (; i < newArray.length - 1; i++) {
                newArray[i] = input.readInt32();
                input.readTag();
              }
              // Last one without readTag.
              newArray[i] = input.readInt32();
              this.replaceChar = newArray;
              break;
            }
            case 42: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              // First pass to compute array length.
              int arrayLength = 0;
              int startPos = input.getPosition();
              while (input.getBytesUntilLimit() > 0) {
                input.readInt32();
                arrayLength++;
              }
              input.rewindToPosition(startPos);
              int i = this.replaceChar == null ? 0 : this.replaceChar.length;
              int[] newArray = new int[i + arrayLength];
              if (i != 0) {
                java.lang.System.arraycopy(this.replaceChar, 0, newArray, 0, i);
              }
              for (; i < newArray.length; i++) {
                newArray[i] = input.readInt32();
              }
              this.replaceChar = newArray;
              input.popLimit(limit);
              break;
            }
            case 50: {
              string_ = input.readString();
              bitField0_ |= 0x00000004;
              break;
            }
          }
        }
      }

      public static Record parseFrom(byte[] data)
          throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
        return com.google.protobuf.nano.MessageNano.mergeFrom(new Record(), data);
      }

      public static Record parseFrom(
              com.google.protobuf.nano.CodedInputByteBufferNano input)
          throws java.io.IOException {
        return new Record().mergeFrom(input);
      }
    }

    private static volatile StringTableTypes[] _emptyArray;
    public static StringTableTypes[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new StringTableTypes[0];
          }
        }
      }
      return _emptyArray;
    }

    // repeated .org.jetbrains.kotlin.serialization.jvm.StringTableTypes.Record record = 1;
    public org.jetbrains.kotlin.serialization.jvm.nano.JvmProtoBuf.StringTableTypes.Record[] record;

    // repeated int32 local_name = 5 [packed = true];
    public int[] localName;

    public StringTableTypes() {
      clear();
    }

    public StringTableTypes clear() {
      record = org.jetbrains.kotlin.serialization.jvm.nano.JvmProtoBuf.StringTableTypes.Record.emptyArray();
      localName = com.google.protobuf.nano.WireFormatNano.EMPTY_INT_ARRAY;
      unknownFieldData = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.record != null && this.record.length > 0) {
        for (int i = 0; i < this.record.length; i++) {
          org.jetbrains.kotlin.serialization.jvm.nano.JvmProtoBuf.StringTableTypes.Record element = this.record[i];
          if (element != null) {
            output.writeMessage(1, element);
          }
        }
      }
      if (this.localName != null && this.localName.length > 0) {
        int dataSize = 0;
        for (int i = 0; i < this.localName.length; i++) {
          int element = this.localName[i];
          dataSize += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeInt32SizeNoTag(element);
        }
        output.writeRawVarint32(42);
        output.writeRawVarint32(dataSize);
        for (int i = 0; i < this.localName.length; i++) {
          output.writeInt32NoTag(this.localName[i]);
        }
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.record != null && this.record.length > 0) {
        for (int i = 0; i < this.record.length; i++) {
          org.jetbrains.kotlin.serialization.jvm.nano.JvmProtoBuf.StringTableTypes.Record element = this.record[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(1, element);
          }
        }
      }
      if (this.localName != null && this.localName.length > 0) {
        int dataSize = 0;
        for (int i = 0; i < this.localName.length; i++) {
          int element = this.localName[i];
          dataSize += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeInt32SizeNoTag(element);
        }
        size += dataSize;
        size += 1;
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeRawVarint32Size(dataSize);
      }
      return size;
    }

    @Override
    public StringTableTypes mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!storeUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 10);
            int i = this.record == null ? 0 : this.record.length;
            org.jetbrains.kotlin.serialization.jvm.nano.JvmProtoBuf.StringTableTypes.Record[] newArray =
                new org.jetbrains.kotlin.serialization.jvm.nano.JvmProtoBuf.StringTableTypes.Record[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.record, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new org.jetbrains.kotlin.serialization.jvm.nano.JvmProtoBuf.StringTableTypes.Record();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new org.jetbrains.kotlin.serialization.jvm.nano.JvmProtoBuf.StringTableTypes.Record();
            input.readMessage(newArray[i]);
            this.record = newArray;
            break;
          }
          case 40: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 40);
            int i = this.localName == null ? 0 : this.localName.length;
            int[] newArray = new int[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.localName, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = input.readInt32();
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = input.readInt32();
            this.localName = newArray;
            break;
          }
          case 42: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            // First pass to compute array length.
            int arrayLength = 0;
            int startPos = input.getPosition();
            while (input.getBytesUntilLimit() > 0) {
              input.readInt32();
              arrayLength++;
            }
            input.rewindToPosition(startPos);
            int i = this.localName == null ? 0 : this.localName.length;
            int[] newArray = new int[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.localName, 0, newArray, 0, i);
            }
            for (; i < newArray.length; i++) {
              newArray[i] = input.readInt32();
            }
            this.localName = newArray;
            input.popLimit(limit);
            break;
          }
        }
      }
    }

    public static StringTableTypes parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new StringTableTypes(), data);
    }

    public static StringTableTypes parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new StringTableTypes().mergeFrom(input);
    }
  }

  public static final class JvmMethodSignature extends
      com.google.protobuf.nano.ExtendableMessageNano<JvmMethodSignature> {

    private static volatile JvmMethodSignature[] _emptyArray;
    public static JvmMethodSignature[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new JvmMethodSignature[0];
          }
        }
      }
      return _emptyArray;
    }

    private int bitField0_;

    // optional int32 name = 1;
    private int name_;
    public int getName() {
      return name_;
    }
    public JvmMethodSignature setName(int value) {
      name_ = value;
      bitField0_ |= 0x00000001;
      return this;
    }
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    public JvmMethodSignature clearName() {
      name_ = 0;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    // optional int32 desc = 2;
    private int desc_;
    public int getDesc() {
      return desc_;
    }
    public JvmMethodSignature setDesc(int value) {
      desc_ = value;
      bitField0_ |= 0x00000002;
      return this;
    }
    public boolean hasDesc() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    public JvmMethodSignature clearDesc() {
      desc_ = 0;
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    public JvmMethodSignature() {
      clear();
    }

    public JvmMethodSignature clear() {
      bitField0_ = 0;
      name_ = 0;
      desc_ = 0;
      unknownFieldData = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, name_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, desc_);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(1, name_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(2, desc_);
      }
      return size;
    }

    @Override
    public JvmMethodSignature mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!storeUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            name_ = input.readInt32();
            bitField0_ |= 0x00000001;
            break;
          }
          case 16: {
            desc_ = input.readInt32();
            bitField0_ |= 0x00000002;
            break;
          }
        }
      }
    }

    public static JvmMethodSignature parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new JvmMethodSignature(), data);
    }

    public static JvmMethodSignature parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new JvmMethodSignature().mergeFrom(input);
    }
  }

  public static final class JvmFieldSignature extends
      com.google.protobuf.nano.ExtendableMessageNano<JvmFieldSignature> {

    private static volatile JvmFieldSignature[] _emptyArray;
    public static JvmFieldSignature[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new JvmFieldSignature[0];
          }
        }
      }
      return _emptyArray;
    }

    private int bitField0_;

    // optional int32 name = 1;
    private int name_;
    public int getName() {
      return name_;
    }
    public JvmFieldSignature setName(int value) {
      name_ = value;
      bitField0_ |= 0x00000001;
      return this;
    }
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    public JvmFieldSignature clearName() {
      name_ = 0;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    // optional int32 desc = 2;
    private int desc_;
    public int getDesc() {
      return desc_;
    }
    public JvmFieldSignature setDesc(int value) {
      desc_ = value;
      bitField0_ |= 0x00000002;
      return this;
    }
    public boolean hasDesc() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    public JvmFieldSignature clearDesc() {
      desc_ = 0;
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    public JvmFieldSignature() {
      clear();
    }

    public JvmFieldSignature clear() {
      bitField0_ = 0;
      name_ = 0;
      desc_ = 0;
      unknownFieldData = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, name_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeInt32(2, desc_);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(1, name_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(2, desc_);
      }
      return size;
    }

    @Override
    public JvmFieldSignature mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!storeUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            name_ = input.readInt32();
            bitField0_ |= 0x00000001;
            break;
          }
          case 16: {
            desc_ = input.readInt32();
            bitField0_ |= 0x00000002;
            break;
          }
        }
      }
    }

    public static JvmFieldSignature parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new JvmFieldSignature(), data);
    }

    public static JvmFieldSignature parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new JvmFieldSignature().mergeFrom(input);
    }
  }

  public static final class JvmPropertySignature extends
      com.google.protobuf.nano.ExtendableMessageNano<JvmPropertySignature> {

    private static volatile JvmPropertySignature[] _emptyArray;
    public static JvmPropertySignature[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new JvmPropertySignature[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .org.jetbrains.kotlin.serialization.jvm.JvmFieldSignature field = 1;
    public org.jetbrains.kotlin.serialization.jvm.nano.JvmProtoBuf.JvmFieldSignature field;

    // optional .org.jetbrains.kotlin.serialization.jvm.JvmMethodSignature synthetic_method = 2;
    public org.jetbrains.kotlin.serialization.jvm.nano.JvmProtoBuf.JvmMethodSignature syntheticMethod;

    // optional .org.jetbrains.kotlin.serialization.jvm.JvmMethodSignature getter = 3;
    public org.jetbrains.kotlin.serialization.jvm.nano.JvmProtoBuf.JvmMethodSignature getter;

    // optional .org.jetbrains.kotlin.serialization.jvm.JvmMethodSignature setter = 4;
    public org.jetbrains.kotlin.serialization.jvm.nano.JvmProtoBuf.JvmMethodSignature setter;

    public JvmPropertySignature() {
      clear();
    }

    public JvmPropertySignature clear() {
      field = null;
      syntheticMethod = null;
      getter = null;
      setter = null;
      unknownFieldData = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.field != null) {
        output.writeMessage(1, this.field);
      }
      if (this.syntheticMethod != null) {
        output.writeMessage(2, this.syntheticMethod);
      }
      if (this.getter != null) {
        output.writeMessage(3, this.getter);
      }
      if (this.setter != null) {
        output.writeMessage(4, this.setter);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.field != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.field);
      }
      if (this.syntheticMethod != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(2, this.syntheticMethod);
      }
      if (this.getter != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(3, this.getter);
      }
      if (this.setter != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(4, this.setter);
      }
      return size;
    }

    @Override
    public JvmPropertySignature mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!storeUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.field == null) {
              this.field = new org.jetbrains.kotlin.serialization.jvm.nano.JvmProtoBuf.JvmFieldSignature();
            }
            input.readMessage(this.field);
            break;
          }
          case 18: {
            if (this.syntheticMethod == null) {
              this.syntheticMethod = new org.jetbrains.kotlin.serialization.jvm.nano.JvmProtoBuf.JvmMethodSignature();
            }
            input.readMessage(this.syntheticMethod);
            break;
          }
          case 26: {
            if (this.getter == null) {
              this.getter = new org.jetbrains.kotlin.serialization.jvm.nano.JvmProtoBuf.JvmMethodSignature();
            }
            input.readMessage(this.getter);
            break;
          }
          case 34: {
            if (this.setter == null) {
              this.setter = new org.jetbrains.kotlin.serialization.jvm.nano.JvmProtoBuf.JvmMethodSignature();
            }
            input.readMessage(this.setter);
            break;
          }
        }
      }
    }

    public static JvmPropertySignature parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new JvmPropertySignature(), data);
    }

    public static JvmPropertySignature parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new JvmPropertySignature().mergeFrom(input);
    }
  }
}
