#!/bin/bash

# TODO: write a proper Makefile or build.xml

CWD=`dirname $0`
HOME=$CWD/../../..

javah -classpath $HOME/out/production/runtime.objc:$HOME/dependencies/bootstrap-compiler/Kotlin/lib/kotlin-runtime.jar -o $CWD/KotlinNative.h jet.objc.Native

# Working path on Mac OS X Lion/Mountain Lion with JDK 6:
# JAVA_INCLUDE=-I/System/Library/Frameworks/JavaVM.framework/Versions/Current/Headers
JAVA_HOME=`/usr/libexec/java_home`
JAVA_INCLUDE="-I$JAVA_HOME/include -I$JAVA_HOME/include/darwin"

c++ -O2 -Wall -Wl,-no_compact_unwind $JAVA_INCLUDE -Iffi -Lffi -lffi -lobjc -dynamiclib $CWD/KotlinNative.cc -o $CWD/libKotlinNative.dylib
